name: Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: Install & Lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      -
        id: install
        run: yarn install
      -
        id: lint
        run: yarn lint

  deploy:
    if: github.ref_name == 'main'
    name: Commit to smallstep/prof
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout smallstep/prof
        uses: actions/checkout@master
        with:
          repository: smallstep/prof
          token: ${{ secrets.PAT }}
          path: './prof'
      -
        name: Setup bot SSH signing key
        uses: webfactory/ssh-agent@v0.7.0
        env:
          HAS_SSH_PRIVATE_KEY: ${{ secrets.STEP_TRAVIS_CI_GH_PRIVATE_SIGNING_KEY != '' }}
        if: ${{ env.HAS_SSH_PRIVATE_KEY == 'true' }}
        with:
          ssh-private-key: |
            ${{ secrets.STEP_TRAVIS_CI_GH_PRIVATE_SIGNING_KEY }}
      -
        name: Update Reference
        id: update_reference
        run: |
          cd ./prof
          git config user.email "eng+ci@smallstep.com"
          git config user.name "step-travis-ci"

          # Configure GH commit signing key.
          git config --global commit.gpgsign true
          git config --global gpg.format ssh
          git config --global user.signingkey "${{ secrets.STEP_TRAVIS_CI_GH_PUBLIC_SIGNING_KEY }}"

          git commit --allow-empty -m "Empty commit triggered by docs ${{ github.sha }}"
          git push origin master
