name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Clone practicalzt
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Clone web repo for site layout
      uses: actions/checkout@v2
      with:
        repository: smallstep/web
        ref: master
        path: ~/work/practicalzt/web
        ssh-key: ${{ secrets.WEB_SSH_KEY }}

    - name: Build and copy web layouts
      run: ./scripts/build-layouts.sh

    - run: yarn install
    - run: yarn build
    - run: tree public

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: public

  deploy:
    name: Deploy
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: website
        path: public
    - name: Upload website files to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: public
        destination: ${{ secrets.GCP_GCS_BUCKET }}/practical-zero-trust
        parent: false
        headers: |-
          cache-control: public, max-age=0
