name: Deploy

on:
  workflow_run:
    workflows: Lint
    branches: main
    types: completed

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Start deploy in private build
        run: |-
          curl -f -s -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token ${{ secrets.TRAVIS_TOKEN }}" \
            -d "{\"branch\": \"master\", \"message\": \"Deploy from docs repo\"}" \
            https://api.travis-ci.com/repo/smallstep%2Fprof/requests
