name: Lint

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Clone practicalzt
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - run: yarn install
    - run: yarn lint
